name: Silo Prediction Add-on
version: "1.0.7"
slug: silo_prediction_addon
description: Silo 0kg predikci√≥ REST API
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: services
boot: auto
webui: "http://[HOST]:[PORT:5000]/predict"
ports:
  5000/tcp: 5000
host_network: true
options: {}
schema: {}
